# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9cc584ac52ac1e265d45e3403dbdfa172e1e4fa9dd923104df4e4790dd0781a50a66d9fddc6790e1b715ebde7b8ff17a9b748571b3c8e930f13f3b4301dfba77

test:
  secret_key_base: c53790793edcc510aabf7fb3617d95fc341f6e3bc2c8fdb657cb630fc3fd6bd73278bfd405efa6721610061d323bcb51a271b78b15b2ef453e9cc58f0b50d6d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
