# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186d37aa137db096391e43af9703686338a93cce296bbaac1956172107394f28852eb00ea8c738b0eaf210f494eb35d5c8d9e5bc0e1783cbd4fc3053b0e60aec

test:
  secret_key_base: b62a2138b61b2a24dedca57d3a77c0174417c11f4e6cd9ea25522c5778c720a544c43c4729d33135ecf28d4fbf7f19f4b2a981d4aacbfad896de36f4676314c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
